INSERT INTO MO_USERINFO (USER_ID, PASSWORD, USER_NAME, LOCK_YN, SIGNUP_DTTM) 
VALUES ('admin', '1234', '관리자', 'N', current_timestamp);

INSERT INTO MO_NationCity
VALUES (1, 'KR', 'South Korea', '', '', 'KWJ', '광주')
, (2, 'KR', 'South Korea', '', '', 'TAE', '대구')
, (3, 'KR', 'South Korea', '', '', 'USN', '울산')
, (4, 'KR', 'South Korea', '', '', 'PUS', '부산')
, (5, 'KR', 'South Korea', '', '', 'HIN', '진주')
, (6, 'KR', 'South Korea', 'GWD', 'Gangwon-do', 'KAG', '강릉')
, (7, 'KR', 'South Korea', '', '', 'CJU', '제주')
, (8, 'KR', 'South Korea', '', '', 'SHO', '속초')
, (9, 'KR', 'South Korea', '', '', 'MPK', '목포')
, (10, 'KR', 'South Korea', '', '', 'RSU', '여수')
, (11, 'KR', 'South Korea', '', '', 'KUV', '군산')
, (12, 'KR', 'South Korea', 'NCC', 'Chungcheongbuk-do', 'CJJ', '청주')
, (13, 'KR', 'South Korea', 'SEL', 'Seoul', 'SEL', '서울')
;

insert into mo_facilities (fclt_id, fclt_name, fclt_img_url)
values ('1', 'Bicycle Storage', '')
, ('2', 'Cafe', '')
, ('3', 'Handcapped', '')
, ('4', 'No Pet Allowed', '')
, ('5', 'Parking', '')
, ('6', 'Picnic Table', '')
, ('7', 'Pool', '')
, ('8', 'Shops', '')
, ('9', 'Wi-fi', '')
;

insert into mo_themes (acmd_theme_id, acmd_theme_name, acmd_theme_img_url)
values ('1', 'Beach Front', '')
, ('2', 'Countryside', '')
, ('3', 'Couple Friendly', '')
, ('4', 'Event & Party', '')
, ('5', 'Family Friendly', '')
, ('6', 'Forest', '')
, ('7', 'Hill Side', '')
, ('8', 'Lake View', '')
, ('9', 'Mountain', '')
, ('10', 'River View', '')
, ('11', 'Stream Side', '')
, ('12', 'Valley', '')
, ('13', 'Pet Allowed', '')
;

insert into mo_activitytypes (actv_type_id, actv_type_name, actv_type_img_url)
values ('1', 'Biking', '')
, ('2', 'Boating', '')
, ('3', 'Hiking', '')
, ('4', 'Fishing', '')
, ('5', 'Trekking', '')
, ('6', 'Climbing', '')
, ('7', 'Horse Riding', '')
, ('8', 'Padding', '')
, ('9', 'Swimming', '')
, ('10', 'Surfing', '')
, ('11', 'Water Leisure', '')
, ('12', 'Wildlife Watching', '')
, ('13', 'Snow Sports', '')
;
commit;